DROP TABLE IF EXISTS riends_list ON DELETE CASCADE;
DROP TABLE IF EXISTS blocked_list ON DELETE CASCADE;


CREATE TABLE friends_list(
  id SERIAL PRIMARY KEY NOT NULL,
  friend FOREIGN KEY REFERENCES gamers(id) NOT NULL,
  added_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  games FOREIGN KEY REFERENCES games_list(id) NOT NULL,
  online BOOLEAN default FALSE
);

CREATE TABLE blocked_list(
  id SERIAL PRIMARY KEY NOT NULL,
  gamer_id FOREIGN KEY NOT NULL,
  added_on TIMESTAMP,
  games_id FOREIGN KEY NOT NULL
);