INSERT INTO genres (name)
VALUES
("Simulation"),
("Racing"),
("Platformer"),
("Sandbox"),
("Puzzlers"),
("Party Games"),
("Hack and Slash"),
("Sport"),
("MMORPG"),
("Indie"),
("Role-playing game"),
("Mobile game"),
("Horror"),
("Real-time Strategy"),
("Strategy"),
("Adventure"),
("Otome"),
("Adult");
