INSERT INTO genres (name, kid_friendly)
VALUES
("Simulation", TRUE)
("Racing", TRUE)
("Platformer", TRUE)
("Sandbox", TRUE)
("Puzzlers", TRUE)
("Party Games", TRUE)
("Survival", TRUE)
("Simulation", TRUE)
